type Color = {
  background: string;
  background2: string;
  background3: string;
  backgroundLight: string;
  backgroundOverlay: string;
  backgroundTrade: string;
  backgroundTrade2: string;
  backgroundTrade3: string;
  tradeBorder: string;
  surface: string;
  onBackground: string;
  onBackgroundDark: string;
  onBackgroundLight: string;
  primary: string;
  onPrimary: string;
  primaryLight: string;
  onPrimaryLight: string;
  primaryHover: string;
  primaryActive: string;
  accent: string;
  positive: string;
  positiveHover: string;
  negative: string;
  negativeHover: string;
  negativeLight: string;
  error: string;
  light: string;
  secondary: string;
  secondaryActive: string;
  tertiary: string;
  onThird: string;
  onSecondary: string;
  hoverActive: string;
  constantDark: string;
  constantDark1: string;
  surfaceFadeActive: string;
  fadeBackground: string;
  constantSurface: string;
  constantLight: string;
  negativeFade: string;
  backgroundTradeInput: string;
  backgroundTradeReverse: string;
  onPositive: string;
  onNegative: string;
};
type Theme = Record<"lightTheme" | "darkTheme", Color>;
const themes: Theme = {
  lightTheme: {
    background: "#ffffff",
    background2: "#F5F7FA",
    background3: "#F1F2F5",
    backgroundLight: "#F5F7FA",
    backgroundOverlay: "#ffffff",
    backgroundTrade: "#F5F7FA",
    backgroundTrade2: "#E6E8EA",
    backgroundTrade3: "#ffffff",
    tradeBorder: "#E1E3E6",
    surface: "#ffffff",
    onBackground: "#111C28",
    onBackgroundDark: "#343D4F",
    onBackgroundLight: "#b7bdc6",
    primary: "#2abda8",
    onPrimary: "#fff",
    primaryLight: "#2ABDA8",
    onPrimaryLight: "#ffffff",
    primaryHover: "#25A895",
    primaryActive: "#229C89",
    accent: "#848E9C",
    positive: "#0ecb81",
    positiveHover: "#2ed191",
    negative: "#f6465d",
    negativeHover: "#ff4265",
    negativeLight: "#fdbab9",
    error: "#cf304a",
    light: "#e6e8ea",
    secondary: "#E1E3E6",
    secondaryActive: "#B7BDC6",
    tertiary: "#0C141D",
    onThird: "#F5F7FA",
    onSecondary: "#111C28",
    hoverActive: "#F5F7FA",
    constantDark: "#111C28",
    constantDark1: "#252B38",
    surfaceFadeActive: "#5DE3CF26",
    fadeBackground: "#DCF2EF",
    constantSurface: "#666D78",
    constantLight: "#ffffff",
    negativeFade: "#fef1f2",
    backgroundTradeInput: "#E1E3E6",
    backgroundTradeReverse: "#343D4F",
    onPositive: "#fff",
    onNegative: "#fff",
  },
  darkTheme: {
    background2: "#0C141D",
    background: "#111C28",
    background3: "#151310",
    backgroundLight: "#0C141D",
    backgroundTrade: "#161A1E",
    backgroundOverlay: "#23282D",
    backgroundTrade2: "#252B38",
    backgroundTrade3: "#111C28",
    tradeBorder: "#252930",
    surface: "#121E2B",
    onBackground: "#F5F7FA",
    onBackgroundDark: "#9BA3B0",
    onBackgroundLight: "#5E6673",
    primary: "#2abda8",
    onPrimary: "#fff",
    primaryLight: "#2ABDA8",
    onPrimaryLight: "#ffffff",
    primaryHover: "#25A895",
    primaryActive: "#229C89",
    accent: "#848E9C",
    positive: "#0ecb81",
    positiveHover: "#2ed191",
    negative: "#f6465d",
    negativeHover: "#ff4265",
    negativeFade: "#fef1f2",
    error: "#cf304a",
    light: "#1F2530",
    secondary: "#474d57",
    secondaryActive: "#5e6673",
    tertiary: "#0C141D",
    onThird: "#F5F7FA",
    onSecondary: "#F5F7FA",
    hoverActive: "#252B38",
    constantDark: "#111C28",
    constantDark1: "#252B38",
    surfaceFadeActive: "#20303D26",
    fadeBackground: "#2D5C56",
    constantSurface: "#5E6673",
    constantLight: "#ffffff",
    backgroundTradeInput: "#2B2F36",
    backgroundTradeReverse: "#dce0e5",
    negativeLight: "#fdbab9",
    onPositive: "#fff",
    onNegative: "#fff",
  },
};

export { themes };
export type { Color as Theme };
